version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    restart: always
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - postgres

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - postgres

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dev.Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=postgres
    ports:
      - "${PORT}:${PORT}"
    networks:
      - postgres
    command: npm run start:dev

volumes:
  db:

networks:
  postgres:
    driver: bridge